language: node_js
node_js:
 - 0.8
env:
 - SKIP_SOLR_TESTS=1
 - SKIP_ETHERPAD_TESTS=1
services:
 - redis-server
 - mongodb
before_script: "npm install --dev"
before_install:
 - sudo apt-get install -qq imagemagick libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
script: "npm test"
branches:
  only:
    - master
